Feature/adjusting for production running
brunofurmon/open-org-chart pull request #31
Opened 2024-10-28 22:31 UTC by bernardolm

Adding config to Redis connection timeout in ms.

2024-10-28 22:57 UTC, brunofurmon approved these changes

2024-10-28 22:59 UTC, brunofurmon requested changes

2024-10-28 22:59 UTC, brunofurmon commented on src/infrastructure/cache/redis.js
> +    connectTimeout: Number(process.env.REDIS_CONN_TIMEOUT_MS)
Add this entry on README as well

2024-10-28 23:21 UTC, bernardolm commented on src/infrastructure/cache/redis.js
> +    connectTimeout: Number(process.env.REDIS_CONN_TIMEOUT_MS)
Done

2024-10-31 01:25 UTC, brunofurmon approved these changes

2024-10-31 01:26 UTC, merged